-- ════════════════════════════════════════════════════════════
-- ⚠️  ARCHIVO DEPRECADO — USA seed_completo.sql EN SU LUGAR
-- ════════════════════════════════════════════════════════════
-- Este archivo usaba UUIDs falsos (cc000001, cc000002, etc.)
-- que no coinciden con los Auth UIDs reales de Supabase.
--
-- EL ARCHIVO CORRECTO ES: db/seed_completo.sql
-- Ese archivo usa los UUID reales de Supabase Auth:
--
-- GOBIERNO:
--   c91c7e1c-...  →  226w0702@zongolica.tecnm.mx  (OPERADOR)
--   2749ea87-...  →  admin@toj.gob.mx             (ADMIN)
--
-- CIUDADANOS (id = auth_user_id):
--   56fd9a8d-...  →  ivanry@gmail.com
--   f96b057f-...  →  janiebauch02@gmail.com
--   d597863e-...  →  joseortegahac@gmail.com
--   a3b0ef9c-...  →  juanrt@gmail.com
--   8b74085f-...  →  pedrogil23@gmail.com
--   7f9969cd-...  →  ramirezrj345@gmail.com
-- ════════════════════════════════════════════════════════════

SELECT '⚠️ Este archivo está deprecado. Usa db/seed_completo.sql' AS aviso;
